---
- name: Asynchronously delete KOps clusters
  ansible.builtin.command:
    argv:
      - kops
      - delete
      - cluster
      - --name
      - "{{ item }}"
      - --yes
      - --state
      - "{{ state_store }}"
  async: 900
  loop: "{{ cluster_names }}"
  poll: 0
  register: async_delete_results

- name: Wait for asynchronous operations to complete
  ansible.builtin.async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ async_delete_results.results }}"
  register: async_delete_poll_results
  until: async_delete_poll_results.finished
  delay: 30
  retries: 30

- name: Clean up ansychronous operations
  ansible.builtin.async_status:
    mode: cleanup
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ async_delete_results.results }}"

- name: Find all route tables associated with kops clusters
  amazon.aws.ec2_vpc_route_table_info:
    filters:
      "tag:Name": "{{ awx_stack.name_prefix }}-public-route-table"
    region: "{{ awx_cluster.aws.region }}"
  register: route_tables_info

- name: Find all subnets associated with route tables' vpcs
  amazon.aws.ec2_vpc_subnet_info:
    filters:
      vpc-id: "{{ item.vpc_id }}"
    region: "{{ awx_cluster.aws.region }}"
  loop: "{{ route_tables_info.route_tables }}"
  register: subnet_info_list

- name: Delete all associated subnets
  amazon.aws.ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ item.vpc_id }}"
    region: "{{ awx_cluster.aws.region }}"
    cidr: "{{ item.cidr_block }}"
  loop: "{{ subnet_info_list.results | sum(attribute='subnets', start=[]) }}"

- name: Delete all associated route tables
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ item.vpc_id }}"
    region: "{{ awx_cluster.aws.region }}"
    route_table_id: "{{ item.id }}"
    lookup: id
    state: absent
  loop: "{{ route_tables_info.route_tables }}"

- name: Delete all associated Internet Gateway
  amazon.aws.ec2_vpc_igw:
    state: absent
    vpc_id: "{{ item.vpc_id }}"
    region: "{{ awx_cluster.aws.region }}"
  loop: "{{ route_tables_info.route_tables }}"

- name: Delete all associated VPCs
  amazon.aws.ec2_vpc_net:
    state: absent
    vpc_id: "{{ item.vpc_id }}"
    region: "{{ awx_cluster.aws.region }}"
  loop: "{{ route_tables_info.route_tables }}"
