---
- name: Take a configurable pause during execution
  hosts:
    - environment
  vars:
    minutes: "{{ pause_duration_in_minutes | default(2) }}"
  tasks:
    - name: Pausing for {{ pause_minutes }} minutes
      ansible.builtin.pause:
        seconds: "{{ minutes | int * 60 }}"
      tags:
        - pause
