---
- name: Task to warmup AWX nodes
  hosts:
    - runner
  tasks:
    - name: Warmup task for AWX task nodes
      ansible.builtin.debug:
        msg: "Attempt to warm up task node"

    - name: Hold for distribution
      ansible.builtin.wait_for:
        timeout: 30