---
apiVersion: itbench.io/v1
kind: GroundTruth
metadata:
  name: scenario-23
spec:
  alerts:
    - KubePodNotReady
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: checkout
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo rollout undo deployment/checkout
            text: Revert the last change done to the manifest.
      - steps:
          - command: kubectl -n otel-demo edit deployment checkout
            text: Manually edit the manifest and replace the invalid image with the correct value.
      - steps:
          - command: kubectl -n otel-demo edit deployment checkout
            text: Manually edit the manifest and replace the node selector to allow Kubernetes to schedule the workload on a supported node (if exists).
