---
apiVersion: itbench.io/v2
kind: AccessRule
metadata:
  name: scenario-30-agent
spec:
  endpoints:
    logs:
      enabled: true
    metrics:
      enabled: true
    topology:
      enabled: true
    traces:
      enabled: true
  namespaces:
    - access: rw
      name: otel-demo
