---
tools_instances:
  clickhouse:
    names:
      main: clickhouse
    namespace: clickhouse
  kubernetes_gateways:
    namespace: kube-gateways
  opentelemetry_collectors:
    names:
      istio: istio
      jaeger: jaeger
      kubernetes_events: kubernetes-events
      kubernetes_objects_snapshot: kubernetes-objects-snapshot
    namespace: opentelemetry-collectors
