---
- name: Import faults docs generation tasks
  ansible.builtin.import_tasks:
    file: generate_faults_docs.yaml
  tags:
    - generate_docs

- name: Import scenarios docs generation tasks
  ansible.builtin.import_tasks:
    file: generate_scenarios_docs.yaml
  tags:
    - generate_docs

- name: Import faults docs validation tasks
  ansible.builtin.import_tasks:
    file: validate_faults_docs.yaml
  tags:
    - validate_docs

- name: Import scenarios docs validation tasks
  ansible.builtin.import_tasks:
    file: validate_scenarios_docs.yaml
  tags:
    - validate_docs
