---
- name: Validate applications library index
  ansible.utils.validate:
    data: "{{ lookup('ansible.builtin.file', 'files/library/applications/index.json') | from_json }}"
    criteria: "{{ lookup('ansible.builtin.file', 'files/library/applications/schema.json') | from_json }}"
    engine: ansible.utils.jsonschema
