---
- name: Validate waiters library index
  ansible.utils.validate:
    data: "{{ lookup('ansible.builtin.file', 'files/library/waiters/index.json') | from_json }}"
    criteria: "{{ lookup('ansible.builtin.file', 'files/library/waiters/schema.json') | from_json }}"
    engine: ansible.utils.jsonschema
