---
apiVersion: itbench.io/v1
kind: AccessRule
metadata:
  name: scenario-50-agent
spec:
  endpoints:
    logs:
      enabled: true
    metrics:
      enabled: true
    topology:
      enabled: true
    traces:
      enabled: true
  namespaces:
    - access: rw
      name: bookinfo
