---
argument_specs:
  generate_files:
    author:
      - Gerard Vanloo
    options:
      scenarios_files_generator:
        required: false
        type: dict
        options:
          options:
            required: false
            type: dict
            options:
              overwrite:
                default: false
                required: false
                type: bool
