---
- name: Import invalid command removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_invalid_command.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.invalid_command }}"
  when:
    - fault_spec.fault.custom.name == 'invalid-command'
    - fault_spec.fault.custom.invalid_command is defined

- name: Import invalid image removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_invalid_image.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.invalid_image }}"
  when:
    - fault_spec.fault.custom.name == 'invalid-image'
    - fault_spec.fault.custom.invalid_image is defined

- name: Import invalid node selector removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_invalid_node_selector.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.invalid_node_selector }}"
  when:
    - fault_spec.fault.custom.name == 'invalid-node-selector'
    - fault_spec.fault.custom.invalid_node_selector is defined

- name: Import misconfigured horizontal pod autoscaler removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_misconfigured_horizontal_pod_autoscaler.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.misconfigured_horizontal_pod_autoscaler }}"
  when:
    - fault_spec.fault.custom.name == 'misconfigured-horizontal-pod-autoscaler'
    - fault_spec.fault.custom.misconfigured_horizontal_pod_autoscaler is defined

- name: Import misconfigured network policy removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_misconfigured_network_policy.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.misconfigured_network_policy }}"
  when:
    - fault_spec.fault.custom.name == 'misconfigured-network-policy'
    - fault_spec.fault.custom.misconfigured_network_policy is defined

- name: Import misconfigured persistent volume claim removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_misconfigured_persistent_volume_claim.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.misconfigured_persitent_volume_claim }}"
  when:
    - fault_spec.fault.custom.name == 'misconfigured-persitent-volume-claim'
    - fault_spec.fault.custom.misconfigured_persitent_volume_claim is defined

- name: Import misconfigured resource quota removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_misconfigured_resource_quota.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.misconfigured_resource_quota }}"
  when:
    - fault_spec.fault.custom.name == 'misconfigured-resource-quota'
    - fault_spec.fault.custom.misconfigured_resource_quota is defined

- name: Import misconfigured service port removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_misconfigured_service_port.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.misconfigured_service_port }}"
  when:
    - fault_spec.fault.custom.name == 'misconfigured-service-port'
    - fault_spec.fault.custom.misconfigured_service_port is defined

- name: Import modify environment variables removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_modify_environment_variables.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.modify_environment_variables }}"
  when:
    - fault_spec.fault.custom.name == 'modify-environment-variables'
    - fault_spec.fault.custom.modify_environment_variables is defined

- name: Import unsupported image removal tasks
  ansible.builtin.import_tasks:
    file: remove_custom_unsupported_image.yaml
  vars:
    spec: "{{ fault_spec.fault.custom.unsupported_image }}"
  when:
    - fault_spec.fault.custom.name == 'unsupported-image'
    - fault_spec.fault.custom.unsupported_image is defined
