apiVersion: itbench.io/v1
kind: ScenarioSpec
metadata:
  labels:
    itbench.io/scenario-variant: none
  name: scenario-47
spec:
  applications:
  - bookInfo:
      enabled: true
      options: {}
  faults:
  - injections:
    - args:
        httpMethods:
        - GET
        kubernetesObject:
          apiVersion: gateway.networking.k8s.io
          kind: Gateway
          metadata:
            name: bookinfo-gateway
            namespace: bookinfo
      id: traffic-denying-istio-gateway-authorization-policy
  tools:
    networking:
      istio:
        enabled: true
    observability:
      events:
        enabled: true
      logs:
        enabled: true
      metrics:
        enabled: true
      topology:
        enabled: true
      traces:
        enabled: true
