---
argument_specs:
  main:
    author:
      - Gerard Vanloo
    options:
      waiters_cluster:
        options:
          kubeconfig:
            required: true
            type: str
        required: true
        type: dict
      waiters_tasks:
        elements: dict
        options:
          args:
            required: true
            type: dict
          id:
            required: true
            type: str
        required: true
        type: list
