---
- name: Import unified recorders based on ClickHouse installation tasks
  ansible.builtin.import_tasks:
    file: install_unified_recorders_clickhouse.yaml
  when:
    - recorders_required.unified.clickhouse | default(true)
