---
- name: Import unified recorders based on ClickHouse uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_unified_recorders_clickhouse.yaml
  when:
    - recorders_required.unified.clickhouse | default(false)
