apiVersion: itbench.io/v1
kind: SilverTruth
metadata:
  name: scenario-105
spec:
  alerts:
  - KubePodCrashLooping
  entities:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: product-catalog
      namespace: otel-demo
  solutions:
  - - steps:
      - command: kubectl -n otel-demo rollout undo deployment/product-catalog
        text: Revert the last change done to the manifest.
    - steps:
      - command: kubectl -n otel-demo edit deployment product-catalog
        text: Manually edit the manifest and replace the invalid command with the
          correct value.
