---
apiVersion: itbench.io/v1
kind: SilverTruth
metadata:
  name: scenario-16
spec:
  alerts: []
  entities:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: shipping
        namespace: otel-demo
  solutions:
    - - steps:
          - command: kubectl -n otel-demo rollout undo deployment/shipping
            text: Revert the last change done to the manifest.
      - steps:
          - command: kubectl -n otel-demo edit deployment shipping
            text: Manually edit the manifest and replace the environment variable(s) value with the correct value(s).
