name: Perform install smoke tests for fault tools

on:
  pull_request:
    branches:
      - main
    paths:
      - sre/roles/fault_tools/*

jobs:
  chaos-mesh:
    name: Attempt installation of Chaos Mesh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-go@v5
        with:
          go-version-file: sre/local_cluster/go.mod
      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Install Python and Ansible dependencies
        run: |
          pip install -r sre/requirements.txt
          ansible-galaxy install -r sre/requirements.yaml
      - name: Create Kind cluster
        run: |
          make -C sre/local_cluster create_cluster
      - name: Run installation smoke test
        run: |
          ansible-playbook sre/manage_tools.yaml --tags "install_tools" --extra-vars "kubeconfig=~/.kube/config" --extra-vars '{"fault_tools": { "chaos_mesh": true }}'
